#!/usr/bin/env bash
#
# Build a Bun-compiled CodeGraph binary for the target platform.
#
# Usage:
#   scripts/build-bun-compile.sh <target>
#     target:      bun-darwin-arm64 | bun-darwin-x64 | bun-linux-x64 |
#                  bun-linux-arm64 | bun-windows-x64 | bun-windows-arm64
#
# Output:
#   release/codegraph-<os>-<arch>[.exe]
set -euo pipefail

TARGET="${1:?usage: build-bun-compile.sh <target> (e.g. bun-darwin-arm64)}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/release"

# Strip the "bun-" prefix for the output filename and derive OS/arch.
ARCH="${TARGET##*-}"   # x64 | arm64
OSFAM="${TARGET%-*}"   # darwin | linux | windows
OSFAM="${OSFAM#bun-}"  # remove bun- prefix
PLAIN_TARGET="${OSFAM}-${ARCH}"

echo "[compile] target=${TARGET} (output: codegraph-${PLAIN_TARGET})"

# --- Step 1: Pre-bundle workers and generate worker-code.ts ---
# Workers with TypeScript syntax can't be loaded as raw files by Worker().
# Pre-bundle each to JS, then embed the JS as string constants in worker-code.ts.
WORKER_CODE="$ROOT/src/extraction/worker-code.ts"
TMPDIR=$(mktemp -d)

echo "[compile] pre-bundling shimmer-worker..."
bun build "$ROOT/src/ui/shimmer-worker.ts" \
  --outdir "$TMPDIR" \
  --target bun 2>&1
SHIMMER_JS=$(cat "$TMPDIR/shimmer-worker.js")

rm -rf "$TMPDIR"

cat > "$WORKER_CODE" << HEREDOC
/**
 * Embedded worker code for compiled binary.
 * GENERATED by scripts/build-bun-compile.sh — do not edit.
 */
export const SHIMMER_WORKER_CODE = $(printf '%s' "$SHIMMER_JS" | node -e 'process.stdout.write(JSON.stringify(require("fs").readFileSync(0,"utf8")))');
export const PARSE_WORKER_CODE = '';
HEREDOC

echo "[compile] generated worker-code.ts ($(wc -c < "$WORKER_CODE") bytes)"

# --- Step 2: Build the compiled binary ---
mkdir -p "$OUT"

OUTFILE="$OUT/codegraph-${PLAIN_TARGET}"
if [ "$OSFAM" = "windows" ]; then
  OUTFILE="${OUTFILE}.exe"
fi

echo "[compile] building → ${OUTFILE}"
bun build --compile \
  --target "$TARGET" \
  "${ROOT}/src/bin/codegraph-compile.ts" \
  --outfile "$OUTFILE"

# --- Step 3: Restore placeholder worker-code.ts ---
cat > "$WORKER_CODE" << 'PLACEHOLDER'
/**
 * Embedded worker code for compiled binary.
 * Placeholder — replaced during build by scripts/build-bun-compile.sh.
 */
export const SHIMMER_WORKER_CODE = '';
export const PARSE_WORKER_CODE = '';
PLACEHOLDER

chmod +x "$OUTFILE"
echo "[compile] wrote ${OUTFILE} ($(du -h "$OUTFILE" | cut -f1))"
